import Comment from "./Icons/Comment";
import Dots from "./Icons/Dots";
import Home from "./Icons/Home";
import Like from "./Icons/Like";
import Message from "./Icons/Message";
import Save from "./Icons/Save";
import User from "./Icons/User";
import Instagram from "./Icons/Instagram";
import New from "./Icons/New";
import Mod from "./Icons/Mod";
import Send from "./Icons/Send";
import Close from "./Icons/Close";
import Moon from "./Icons/Moon";
import Sun from "./Icons/Sun";

export const CommentIcon = Comment;
export const DotsIcon = Dots;
export const HomeIcon = Home;
export const LikeIcon = Like;
export const MessageIcon = Message;
export const SaveIcon = Save;
export const UserIcon = User;
export const InstagramIcon = Instagram;
export const NewIcon = New;
export const ModIcon = Mod;
export const SendIcon = Send;
export const CloseIcon = Close;
export const MoonIcon = Moon;
export const SunIcon = Sun;